name: "CI"
on: [push, pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  DEFAULT_JAVA_VERSION: 21
  DEFAULT_JAVA_DISTRIBUTION: 'microsoft'

jobs:
  build:
    name: Build for Java ${{ matrix.java }} on ${{ matrix.distribution }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        java:
          - 21
          - 22
          - 23
        distribution:
          - 'adopt-hotspot'
          - 'oracle'
        include:
          - java: 21
            distribution: 'microsoft'
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: 'Validate Gradle wrapper'
        uses: gradle/actions/wrapper-validation@v3
      - name: 'Setup Java'
        uses: actions/setup-java@v4
        with:
          distribution: ${{ matrix.distribution }}
          java-version: ${{ matrix.java }}
      - name: 'Setup Gradle'
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: wrapper
          cache-read-only: false
      - name: 'Build'
        run: ./gradlew runFinalJar
